### ISSUE TITLE
not able to achieve the same excellent results

### ISSUE THREAD

**Issue by xiyang2002** [Atik-Ahamed/TimeMachine#8]
Hello, I appreciate the compliment on your ideas, but I have run the etth1.sh file using the parameters you provided without any modifications, and I'm not able to achieve the same excellent results as described in your paper.
![2GBX)UOYIDCMF11@F~T)M29](https://github.com/Atik-Ahamed/TimeMachine/assets/147385689/b7fb6d76-f1d4-4e15-bc05-bcb6a7dcf261)
![8 R(XQ QLWQ TBP`R8{0A~V](https://github.com/Atik-Ahamed/TimeMachine/assets/147385689/cf9ca9c0-0284-49ea-81d6-ad23d4a8111d)
![L4Z8}{H 7DH%B$%D4$GR5SX](https://github.com/Atik-Ahamed/TimeMachine/assets/147385689/b28cee3b-035d-420e-a7ad-a201134f5281)
![MTOBUUYSF)7F){S_~O2~R$C](https://github.com/Atik-Ahamed/TimeMachine/assets/147385689/cffa68a0-9741-4509-b413-a6580b579bd1)

**Comment by Atik-Ahamed** [comment]
Thanks for trying our code. We didn't observe this difference. Can you please share the full logs for the experiments you've run?

**Comment by xiyang2002** [comment]
> Thanks for trying our code. We didn't observe this difference. Can you please share the full logs for the experiments you've run?

[TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15464279/TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log)
Please take a look at the complete log file.
[TimeMachine_ETTh1_96_192_512_64_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15464281/TimeMachine_ETTh1_96_192_512_64_0.7_1_1_256_2_1.log)
[TimeMachine_ETTh1_96_336_512_128_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15464282/TimeMachine_ETTh1_96_336_512_128_0.7_1_1_256_2_1.log)
[TimeMachine_ETTh1_96_720_128_16_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15464283/TimeMachine_ETTh1_96_720_128_16_0.7_1_1_256_2_1.log)

and etth1.sh

![Uploading 8JNZH5AR}O$GJ@WOJ)OPPD3.png…]()

**Comment by Atik-Ahamed** [comment]
Thank you for taking the time to review our code and experiments. We appreciate your diligence in trying to replicate our results. After re-running our experiments for ETTh1, we've attached the log files that match the performances reported in our paper. Our investigation revealed that the batch size can affect performance, which is why we used a batch size of 512 for ETTh1 and achieved the results in Table 2. We mentioned in Section 4.2 of our paper, that we tried varying batch sizes for different datasets. We kindly request that you try setting the batch size to 512 for ETTh1. Please let us know if this resolves any discrepancies. Additionally, we'd like to clarify that the scripts uploaded to GitHub were provided as examples, and we may update them to reflect the exact batch sizes used to achieve the results in Table 2.
[TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473585/TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log)
[TimeMachine_ETTh1_96_192_512_64_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473586/TimeMachine_ETTh1_96_192_512_64_0.7_1_1_256_2_1.log)
[TimeMachine_ETTh1_96_336_512_128_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473587/TimeMachine_ETTh1_96_336_512_128_0.7_1_1_256_2_1.log)
[TimeMachine_ETTh1_96_720_128_16_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473588/TimeMachine_ETTh1_96_720_128_16_0.7_1_1_256_2_1.log)

**Comment by xiyang2002** [comment]
Thank you for your patient reply. In other words, different datasets require different batch sizes. Just a small suggestion, you can add this to your statement or modify the sh file to avoid misunderstanding. Finally, thank you again for your work and response。

**Comment by Atik-Ahamed** [comment]
Once again, thank you for your input and suggestion. We would like to incorporate the suggestion.

**Comment by yiyiwwang** [comment]
> Thank you for taking the time to review our code and experiments. We appreciate your diligence in trying to replicate our results. After re-running our experiments for ETTh1, we've attached the log files that match the performances reported in our paper. Our investigation revealed that the batch size can affect performance, which is why we used a batch size of 512 for ETTh1 and achieved the results in Table 2. We mentioned in Section 4.2 of our paper, that we tried varying batch sizes for different datasets. We kindly request that you try setting the batch size to 512 for ETTh1. Please let us know if this resolves any discrepancies. Additionally, we'd like to clarify that the scripts uploaded to GitHub were provided as examples, and we may update them to reflect the exact batch sizes used to achieve the results in Table 2. [TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473585/TimeMachine_ETTh1_96_96_512_32_0.7_1_1_256_2_1.log) [TimeMachine_ETTh1_96_192_512_64_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473586/TimeMachine_ETTh1_96_192_512_64_0.7_1_1_256_2_1.log) [TimeMachine_ETTh1_96_336_512_128_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473587/TimeMachine_ETTh1_96_336_512_128_0.7_1_1_256_2_1.log) [TimeMachine_ETTh1_96_720_128_16_0.7_1_1_256_2_1.log](https://github.com/Atik-Ahamed/TimeMachine/files/15473588/TimeMachine_ETTh1_96_720_128_16_0.7_1_1_256_2_1.log)

Could you please explain why your method is affected by the batch size so much?
 I have compared the average mse on etth1 with batch size 32 and batch size 512: 0.45 vs. 0.42. 
But if I increase the batch size on other methods like iTransformer on etth1, the performance becomes worse.
Thanks very much.

**Comment by liuquangao** [comment]
The author used 'drop_1ast=True' in data_factory, which means that the last batch of data was completely discarded during testing, resulting in unreliable results, especially under the 512 batch size setting.

**Comment by liuquangao** [comment]
https://github.com/VEWOXIC/FITS/issues/2

**Comment by liuquangao** [comment]
The same issue has also arisen in other works：https://github.com/VEWOXIC/FITS/issues/2

**Comment by Atik-Ahamed** [comment]
Thanks a lot for your interest and for pointing out the issue @liuquangao. However, as you pointed out many other works have this issue. Our work was followed by PatchTST's code. You may try to set the batch_size = 1 for the test set, as an workaround. We will try to address this in further ways!

**Comment by largraf** [comment]
Hello, I saw that in the data_factory.py, in the data_provider methods, you use drop_last=True for the test loader.
Doesn't this lead to the evaluation only considering the first part of the test set? Especially for large batch sizes.
This would explain why the performance is strongly dependent on the batch size. Since this determines how much of the test set is dropped in the end.

I tested on etth2, and found that performance gets worse if drop_last is set to False.

As you have pointed out, PatchTST appears to make the same mistake in their code.
Given how much this influences performance, this seems to be a large issue, for making fair comparisons between different algorithms.
Please let me know, if I have missed something. 
Thanks for the great work, and for sharing the code.
